'use client'
import Script from "next/script";
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const script = "document.documentElement.classList.add('js')"
  const src = "https://unpkg.com/taos@1.0.5/dist/taos.js"
  return (
    <html lang="en" className="scroll-smooth">
      <head>
      <Script>
        {script}
      </Script>
      </head>
      <body >
        {children}
        <script src={src}></script>
      </body>
    </html>
  );
}
